In [1]:
import pandas as pd
import numpy as np

logSZ = pd.read_csv(r'/mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.164/Logs_full/mdLog_SZ_20201208_0958.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice", "numTrades"]]
logSZ1 = pd.read_csv(r'/mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.161/Logs_full/mdLog_SZ_20201208_1000.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice", "numTrades"]]
print("original data source type: ")
print(logSZ["source"].unique())
print("new data source type: ")
print(logSZ1["source"].unique())
print(logSZ["time"].unique())
print(logSZ1["time"].unique())

original data source type:
[24]
new data source type:
[31]
['09:58:54.000' '09:58:57.000' '09:59:00.000' '09:59:03.000'
 '09:59:06.000' '09:59:09.000' '09:59:12.000' '09:59:15.000'
 '09:59:18.000' '09:59:21.000' '09:59:24.000' '09:59:27.000'
 '09:59:30.000' '09:59:33.000' '09:59:36.000' '09:59:39.000'
 '09:59:42.000' '09:59:45.000' '09:59:48.000' '09:59:51.000'
 '09:59:54.000' '09:59:57.000' '10:00:00.000' '10:00:03.000'
 '10:00:06.000' '10:00:09.000' '10:00:12.000' '10:00:15.000'
 '10:00:18.000' '10:00:21.000' '10:00:24.000' '10:00:27.000'
 '10:00:30.000' '10:00:33.000' '10:00:36.000' '10:00:39.000'
 '10:00:42.000' '10:00:45.000' '10:00:48.000' '10:00:51.000'
 '10:00:54.000' '10:00:57.000' '10:01:00.000' '10:01:03.000'
 '10:01:06.000' '10:01:09.000' '10:01:12.000' '10:01:15.000'
 '10:01:18.000' '10:01:21.000' '10:01:24.000' '10:01:27.000'
 '10:01:30.000' '10:01:33.000' '10:01:36.000' '10:01:39.000'
 '10:01:42.000' '10:01:45.000' '10:01:48.000' '10:01:51.000'
 '10:01:54.000' '10:01:57.000' '10:02:00.000' '10:02:03.000'
 '10:02:06.000' '10:02:09.000' '10:02:12.000' '10:02:15.000'
 '10:02:18.000' '10:02:21.000' '10:02:24.000' '10:02:27.000'
 '10:02:30.000' '10:02:33.000' '10:02:36.000' '10:02:39.000'
 '10:02:42.000' '10:02:45.000' '10:02:48.000' '10:02:51.000'
 '10:02:54.000' '10:02:57.000' '10:03:00.000' '10:03:03.000'
 '10:03:06.000' '10:03:09.000' '10:03:12.000' '10:03:15.000'
 '10:03:18.000' '10:03:21.000' '10:03:24.000' '10:03:27.000'
 '10:03:30.000' '10:03:33.000' '10:03:36.000' '10:03:39.000'
 '10:03:42.000' '10:03:45.000' '10:03:48.000' '10:03:51.000'
 '10:03:54.000' '10:03:57.000' '10:04:00.000' '10:04:03.000'
 '10:04:06.000' '10:04:09.000' '10:04:12.000' '10:04:15.000'
 '10:04:18.000' '10:04:21.000' '10:04:24.000' '10:04:27.000'
 '10:04:30.000' '10:04:33.000' '10:04:36.000' '10:04:39.000'
 '10:04:42.000' '10:04:45.000' '10:04:48.000' '10:04:51.000'
 '10:04:54.000' '10:04:57.000' '10:05:00.000' '10:05:03.000'
 '10:05:06.000' '10:05:09.000' '10:05:12.000' '10:05:15.000'
 '10:05:18.000' '10:05:21.000' '10:05:24.000' '10:05:27.000'
 '10:05:30.000' '10:05:33.000' '10:05:36.000' '10:05:39.000'
 '10:05:42.000' '10:05:45.000' '10:05:48.000' '10:05:51.000'
 '10:05:54.000' '10:05:57.000' '10:06:00.000' '10:06:03.000'
 '10:06:06.000' '10:06:09.000' '10:06:12.000' '10:06:15.000'
 '10:06:18.000' '10:06:21.000' '10:06:24.000' '10:06:27.000'
 '10:06:30.000' '10:06:33.000' '10:06:36.000' '10:06:39.000'
 '10:06:42.000' '10:06:45.000' '10:06:48.000' '10:06:51.000'
 '10:06:54.000' '10:06:57.000' '10:07:00.000' '10:07:03.000'
 '10:07:06.000' '10:07:09.000' '10:07:12.000' '10:07:15.000'
 '10:07:18.000' '10:07:21.000' '10:07:24.000' '10:07:27.000'
 '10:07:30.000' '10:07:33.000' '10:07:36.000' '10:07:39.000'
 '10:07:42.000' '10:07:45.000' '10:07:48.000' '10:07:51.000'
 '10:07:54.000' '10:07:57.000' '10:08:00.000' '10:08:03.000'
 '10:08:06.000' '10:08:09.000' '10:08:12.000' '10:08:15.000'
 '10:08:18.000' '10:08:21.000' '10:08:24.000' '10:08:27.000'
 '10:08:30.000' '10:08:33.000' '10:08:36.000' '10:08:39.000'
 '10:08:42.000' '10:08:45.000' '10:08:48.000' '10:08:51.000'
 '10:08:54.000' '10:08:57.000' '10:09:00.000' '10:09:03.000'
 '10:09:06.000' '10:09:09.000' '10:09:12.000' '10:09:15.000'
 '10:09:18.000' '10:09:21.000' '10:09:24.000' '10:09:27.000'
 '10:09:30.000' '10:09:33.000' '10:09:36.000' '10:09:39.000'
 '10:09:42.000' '10:09:45.000' '10:09:48.000' '10:09:51.000'
 '10:09:54.000' '10:09:57.000' '10:10:00.000' '10:10:03.000'
 '10:10:06.000' '10:10:09.000' '10:10:12.000' '10:10:15.000'
 '10:10:18.000' '10:10:21.000' '10:10:24.000' '10:10:27.000'
 '10:10:30.000' '10:10:33.000' '10:10:36.000' '10:10:39.000'
 '10:10:42.000' '10:10:45.000' '10:10:48.000' '10:10:51.000'
 '10:10:54.000' '10:10:57.000' '10:11:00.000' '10:11:03.000'
 '10:11:06.000' '10:11:09.000' '10:11:12.000' '10:11:15.000'
 '10:11:18.000' '10:11:21.000' '10:11:24.000' '10:11:27.000'
 '10:11:30.000' '10:11:33.000' '10:11:36.000' '10:11:39.000'
 '10:11:42.000' '10:11:45.000' '10:11:48.000' '10:11:51.000'
 '10:11:54.000' '10:11:57.000' '10:12:00.000' '10:12:03.000'
 '10:12:06.000' '10:12:09.000' '10:12:12.000' '10:12:15.000'
 '10:12:18.000' '10:12:21.000' '10:12:24.000' '10:12:27.000'
 '10:12:30.000' '10:12:33.000' '10:12:36.000' '10:12:39.000'
 '10:12:42.000' '10:12:45.000' '10:12:48.000' '10:12:51.000'
 '10:12:54.000' '10:12:57.000' '10:13:00.000' '10:13:03.000'
 '10:13:06.000' '10:13:09.000' '10:13:12.000' '10:13:15.000'
 '10:13:18.000' '10:13:21.000' '10:13:24.000' '10:13:27.000'
 '10:13:30.000' '10:13:33.000' '10:13:36.000' '10:13:39.000'
 '10:13:42.000' '10:13:45.000' '10:13:48.000' '10:13:51.000'
 '10:13:54.000' '10:13:57.000' '10:14:00.000' '10:14:03.000'
 '10:14:06.000' '10:14:09.000' '10:14:12.000' '10:14:15.000'
 '10:14:18.000' '10:14:21.000' '10:14:24.000' '10:14:27.000'
 '10:14:30.000' '10:14:33.000' '10:14:36.000' '10:14:39.000'
 '10:14:42.000' '10:14:45.000' '10:14:48.000' '10:14:51.000'
 '10:14:54.000' '10:14:57.000' '10:15:00.000' '10:15:03.000'
 '10:15:06.000' '10:15:09.000' '10:15:12.000' '10:15:15.000'
 '10:15:18.000' '10:15:21.000' '10:15:24.000' '10:15:27.000'
 '10:15:30.000' '10:15:33.000' '10:15:36.000' '10:15:39.000'
 '10:15:42.000' '10:15:45.000' '10:15:48.000' '10:15:51.000'
 '10:15:54.000' '10:15:57.000' '10:16:00.000' '10:16:03.000'
 '10:16:06.000' '10:16:09.000' '10:16:12.000' '10:16:15.000'
 '10:16:18.000' '10:16:21.000' '10:16:24.000' '10:16:27.000'
 '10:16:30.000' '10:16:33.000' '10:16:36.000' '10:16:39.000'
 '10:16:42.000' '10:16:45.000' '10:16:48.000' '10:16:51.000'
 '10:16:54.000' '10:16:57.000' '10:17:00.000' '10:17:03.000'
 '10:17:06.000' '10:17:09.000' '10:17:12.000' '10:17:15.000'
 '10:17:18.000' '10:17:21.000' '10:17:24.000' '10:17:27.000'
 '10:17:30.000' '10:17:33.000' '10:17:36.000' '10:17:39.000'
 '10:17:42.000' '10:17:45.000' '10:17:48.000' '10:17:51.000'
 '10:17:54.000' '10:17:57.000' '10:18:00.000' '10:18:03.000'
 '10:18:06.000' '10:18:09.000' '10:18:12.000' '10:18:15.000'
 '10:18:18.000' '10:18:21.000' '10:18:24.000' '10:18:27.000'
 '10:18:30.000' '10:18:33.000' '10:18:36.000' '10:18:39.000'
 '10:18:42.000' '10:18:45.000' '10:18:48.000' '10:18:51.000'
 '10:18:54.000' '10:18:57.000' '10:19:00.000' '10:19:03.000'
 '10:19:06.000' '10:19:09.000' '10:19:12.000' '10:19:15.000'
 '10:19:18.000' '10:19:21.000' '10:19:24.000' '10:19:27.000'
 '10:19:30.000' '10:19:33.000' '10:19:36.000' '10:19:39.000'
 '10:19:42.000' '10:19:45.000' '10:19:48.000' '10:19:51.000'
 '10:19:54.000' '10:19:57.000' '10:20:00.000' '10:20:03.000'
 '10:20:06.000' '10:20:09.000' '10:20:12.000' '10:20:15.000'
 '10:20:18.000' '10:20:21.000' '10:20:24.000' '10:20:27.000'
 '10:20:30.000' '10:20:33.000' '10:20:36.000' '10:20:39.000'
 '10:20:42.000' '10:20:45.000' '10:20:48.000' '10:20:51.000'
 '10:20:54.000' '10:20:57.000' '10:21:00.000' '10:21:03.000'
 '10:21:06.000' '10:21:09.000' '10:21:12.000' '10:21:15.000'
 '10:21:18.000' '10:21:21.000' '10:21:24.000' '10:21:27.000'
 '10:21:30.000' '10:21:33.000' '10:21:36.000' '10:21:39.000'
 '10:21:42.000' '10:21:45.000' '10:21:48.000' '10:21:51.000'
 '10:21:54.000' '10:21:57.000' '10:22:00.000' '10:22:03.000'
 '10:22:06.000' '10:22:09.000' '10:22:12.000' '10:22:15.000'
 '10:22:18.000' '10:22:21.000' '10:22:24.000' '10:22:27.000'
 '10:22:30.000' '10:22:33.000' '10:22:36.000' '10:22:39.000'
 '10:22:42.000' '10:22:45.000' '10:22:48.000' '10:22:51.000'
 '10:22:54.000' '10:22:57.000' '10:23:00.000' '10:23:03.000'
 '10:23:06.000' '10:23:09.000' '10:23:12.000' '10:23:15.000'
 '10:23:18.000' '10:23:21.000' '10:23:24.000' '10:23:27.000'
 '10:23:30.000' '10:23:33.000' '10:23:36.000' '10:23:39.000'
 '10:23:42.000' '10:23:45.000' '10:23:48.000' '10:23:51.000'
 '10:23:54.000' '10:23:57.000' '10:24:00.000' '10:24:03.000'
 '10:24:06.000' '10:24:09.000' '10:24:12.000' '10:24:15.000'
 '10:24:18.000' '10:24:21.000' '10:24:24.000' '10:24:27.000'
 '10:24:30.000' '10:24:33.000' '10:24:36.000' '10:24:39.000'
 '10:24:42.000' '10:24:45.000' '10:24:48.000' '10:24:51.000'
 '10:24:54.000' '10:24:57.000' '10:25:00.000' '10:25:03.000'
 '10:25:06.000' '10:25:09.000' '10:25:12.000' '10:25:15.000'
 '10:25:18.000' '10:25:21.000' '10:25:24.000' '10:25:27.000'
 '10:25:30.000' '10:25:33.000' '10:25:36.000' '10:25:39.000'
 '10:25:42.000' '10:25:45.000' '10:25:48.000' '10:25:51.000'
 '10:25:54.000' '10:25:57.000' '10:26:00.000' '10:26:03.000'
 '10:26:06.000' '10:26:09.000' '10:26:12.000' '10:26:15.000'
 '10:26:18.000' '10:26:21.000' '10:26:24.000' '10:26:27.000'
 '10:26:30.000' '10:26:33.000' '10:26:36.000' '10:26:39.000'
 '10:26:42.000' '10:26:45.000' '10:26:48.000' '10:26:51.000'
 '10:26:54.000' '10:26:57.000' '10:27:00.000' '10:27:03.000'
 '10:27:06.000' '10:27:09.000' '10:27:12.000' '10:27:15.000'
 '10:27:18.000' '10:27:21.000' '10:27:24.000' '10:27:27.000'
 '10:27:30.000' '10:27:33.000' '10:27:36.000' '10:27:39.000'
 '10:27:42.000' '10:27:45.000' '10:27:48.000' '10:27:51.000'
 '10:27:54.000' '10:27:57.000' '10:28:00.000' '10:28:03.000'
 '10:28:06.000' '10:28:09.000' '10:28:12.000' '10:28:15.000'
 '10:28:18.000' '10:28:21.000' '10:28:24.000' '10:28:27.000'
 '10:28:30.000' '10:28:33.000' '10:28:36.000' '10:28:39.000'
 '10:28:42.000' '10:28:45.000' '10:28:48.000' '10:28:51.000'
 '10:28:54.000' '10:28:57.000' '10:29:00.000' '10:29:03.000'
 '10:29:06.000' '10:29:09.000' '10:29:12.000' '10:29:15.000'
 '10:29:18.000' '10:29:21.000' '10:29:24.000' '10:29:27.000'
 '10:29:30.000' '10:29:33.000' '10:29:36.000' '10:29:39.000'
 '10:29:42.000' '10:29:45.000' '10:29:48.000' '10:29:51.000'
 '10:29:54.000' '10:29:57.000' '10:30:00.000' '10:30:03.000'
 '10:30:06.000' '10:30:09.000' '10:30:12.000' '10:30:15.000'
 '10:30:18.000' '10:30:21.000' '10:30:24.000' '10:30:27.000'
 '10:30:30.000' '10:30:33.000' '10:30:36.000' '10:30:39.000'
 '10:30:42.000' '10:30:45.000' '10:30:48.000' '10:30:51.000'
 '10:30:54.000' '10:30:57.000' '10:31:00.000' '10:31:03.000'
 '10:31:06.000' '10:31:09.000' '10:31:12.000' '10:31:15.000'
 '10:31:18.000' '10:31:21.000' '10:31:24.000' '10:31:27.000'
 '10:31:30.000' '10:31:33.000' '10:31:36.000' '10:31:39.000'
 '10:31:42.000' '10:31:45.000' '10:31:48.000' '10:31:51.000'
 '10:31:54.000' '10:31:57.000' '10:32:00.000' '10:32:03.000'
 '10:32:06.000' '10:32:09.000' '10:32:12.000' '10:32:15.000'
 '10:32:18.000' '10:32:21.000' '10:32:24.000' '10:32:27.000'
 '10:32:30.000' '10:32:33.000' '10:32:36.000' '10:32:39.000'
 '10:32:42.000' '10:32:45.000' '10:32:48.000' '10:32:51.000'
 '10:32:54.000' '10:32:57.000' '10:33:00.000' '10:33:03.000'
 '10:33:06.000' '10:33:09.000' '10:33:12.000' '10:33:15.000'
 '10:33:18.000' '10:33:21.000' '10:33:24.000' '10:33:27.000'
 '10:33:30.000' '10:33:33.000' '10:33:36.000' '10:33:39.000'
 '10:33:42.000' '10:33:45.000' '10:33:48.000' '10:33:51.000'
 '10:33:54.000' '10:33:57.000' '10:34:00.000' '10:34:03.000'
 '10:34:06.000' '10:34:09.000' '10:34:12.000' '10:34:15.000'
 '10:34:18.000' '10:34:21.000' '10:34:24.000' '10:34:27.000'
 '10:34:30.000' '10:34:33.000' '10:34:36.000' '10:34:39.000'
 '10:34:42.000' '10:34:45.000' '10:34:48.000' '10:34:51.000'
 '10:34:54.000' '10:34:57.000' '10:35:00.000' '10:35:03.000'
 '10:35:06.000' '10:35:09.000' '10:35:12.000' '10:35:15.000'
 '10:35:18.000' '10:35:21.000' '10:35:24.000' '10:35:27.000'
 '10:35:30.000' '10:35:33.000' '10:35:36.000' '10:35:39.000'
 '10:35:42.000' '10:35:45.000' '10:35:48.000' '10:35:51.000'
 '10:35:54.000' '10:35:57.000' '10:36:00.000' '10:36:03.000'
 '10:36:06.000' '10:36:09.000' '10:36:12.000' '10:36:15.000'
 '10:36:18.000' '10:36:21.000' '10:36:24.000' '10:36:27.000'
 '10:36:30.000' '10:36:33.000' '10:36:36.000' '10:36:39.000'
 '10:36:42.000' '10:36:45.000' '10:36:48.000' '10:36:51.000'
 '10:36:54.000' '10:36:57.000' '10:37:00.000' '10:37:03.000'
 '10:37:06.000' '10:37:09.000' '10:37:12.000' '10:37:15.000'
 '10:37:18.000' '10:37:21.000' '10:37:24.000' '10:37:27.000'
 '10:37:30.000' '10:37:33.000' '10:37:36.000' '10:37:39.000']

['10:00:06.000' '10:00:09.000' '10:00:12.000' ... '15:27:15.000'
 '15:27:30.000' '15:27:45.000']

In [2]:
pd.set_option('max_columns', 200)
logSZ1["time"] = logSZ1["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))
logSZ["time"] = logSZ["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))

display(logSZ[(logSZ["StockID"] == 1) & (logSZ["time"] >= 112000000) & (logSZ["time"] <= 113000000)])
display(logSZ1[(logSZ1["StockID"] == 1) & (logSZ1["time"] >= 112000000) & (logSZ1["time"] <= 113000000)])

Empty DataFrame
Columns: [clockAtArrival, sequenceNo, source, StockID, exchange, time, cum_volume, cum_amount, close, bid1p, bid2p, bid3p, bid4p, bid5p, bid1q, bid2q, bid3q, bid4q, bid5q, ask1p, ask2p, ask3p, ask4p, ask5p, ask1q, ask2q, ask3q, ask4q, ask5q, openPrice, numTrades]
Index: []

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
2444518,1607397600598714,31369472,31,1,SZ,112000000,39065457,732507460.0,18.56,18.56,18.55,18.54,18.53,18.52,20900,165001,50300,162861,281100,18.57,18.58,18.59,18.60,18.61,29800,6000,2300,55635,6400,18.92,38383
2445849,1607397603599387,31386056,31,1,SZ,112003000,39071372,732617287.0,18.57,18.56,18.55,18.54,18.53,18.52,26185,165001,51300,165461,281100,18.57,18.58,18.59,18.60,18.61,25100,6000,2300,55635,6400,18.92,38393
2447250,1607397606598229,31402265,31,1,SZ,112006000,39074772,732680416.0,18.57,18.56,18.55,18.54,18.53,18.52,27885,166001,51200,166761,281100,18.57,18.58,18.59,18.60,18.61,22700,6000,2300,55635,6400,18.92,38397
2448689,1607397609598417,31418678,31,1,SZ,112009000,39075872,732700832.0,18.56,18.56,18.55,18.54,18.53,18.52,26985,166001,51200,166761,281100,18.57,18.58,18.59,18.60,18.61,22700,6000,2300,55635,6400,18.92,38401
2450146,1607397612599058,31436352,31,1,SZ,112012000,39076610,732714530.0,18.56,18.56,18.55,18.54,18.53,18.52,26847,166001,51200,167361,281100,18.57,18.58,18.59,18.60,18.61,22900,6000,2300,56835,6400,18.92,38405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2713051,1607398188593080,34129545,31,1,SZ,112948000,41779027,782894372.0,18.55,18.55,18.54,18.53,18.52,18.51,41296,77800,150835,273500,338300,18.56,18.57,18.58,18.59,18.60,58300,171201,8700,10300,257649,18.92,40770
2714265,1607398191593113,34139693,31,1,SZ,112951000,41788027,783061333.0,18.55,18.55,18.54,18.53,18.52,18.51,38396,77800,150935,273800,338300,18.56,18.57,18.58,18.59,18.60,57200,171201,8700,10300,257649,18.92,40792
2715455,1607398194593568,34151069,31,1,SZ,112954000,41788565,783071317.0,18.56,18.55,18.54,18.53,18.52,18.51,39858,77800,150935,273800,338300,18.56,18.57,18.58,18.59,18.60,89800,168001,8700,10300,257649,18.92,40795
2716760,1607398197593813,34161947,31,1,SZ,112957000,41790065,783099147.0,18.56,18.55,18.54,18.53,18.52,18.51,45158,78000,151035,273800,338300,18.56,18.57,18.58,18.59,18.60,111300,168001,8700,10300,257649,18.92,40800
2717976,1607398200592823,34170924,31,1,SZ,113000000,41822765,783705738.0,18.56,18.55,18.54,18.53,18.52,18.51,13658,77800,151035,273800,338300,18.56,18.57,18.58,18.59,18.60,110700,168001,8700,10300,257649,18.92,40842

In [21]:
data1 = logSZ[(logSZ["cum_volume"] > 0) & (logSZ["source"] == 24)]
data2 = logSZ1[(logSZ1["cum_volume"] > 0) & (logSZ1["source"] == 31)]

columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice", "numTrades"]
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)
if n1 != n2:
    sl = list(set(data1_1["StockID"].unique()) & (set(data2_1["StockID"].unique())))
    data1_1 = data1_1[data1_1["StockID"].isin(sl)]
    data2_1 = data2_1[data2_1["StockID"].isin(sl)]
data1_1['cum_amount'] = data1_1['cum_amount'].round(2)
data2_1['cum_amount'] = data2_1['cum_amount'].round(2)
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["sequenceNo_y"])])
    print(len(test[np.isnan(test["sequenceNo_y"])])/n1)
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(test[np.isnan(test["sequenceNo_x"])])
    display(n2-n1)

2128
2128
1207595
5829472
5869468
-----------------------------------------------

'test is not complete:'

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
0,0.0,1.607393e+15,6586.0,24.0,2,SZ,95854000.0,10343101,3.047514e+08,29.42,29.42,29.41,29.40,29.39,29.38,400,41100,27600,30400,46600,29.43,29.44,29.45,29.46,29.48,2500,20000,3500,3800,3400,29.45,10285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.607393e+15,6588.0,24.0,11,SZ,95854000.0,1164281,1.537601e+07,13.21,13.21,13.20,13.19,13.18,13.17,1000,26200,9300,19200,10300,13.22,13.23,13.25,13.26,13.27,23600,898200,16000,900,1500,13.24,1820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,1.607393e+15,6589.0,24.0,12,SZ,95854000.0,11367712,7.546592e+07,6.62,6.61,6.60,6.59,6.58,6.57,69400,247700,127300,176100,121400,6.62,6.63,6.64,6.65,6.66,88000,74671,21276,32828,151000,6.63,6076,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,1.607393e+15,6590.0,24.0,14,SZ,95854000.0,249600,2.275827e+06,9.11,9.11,9.10,9.09,9.08,9.07,25400,28000,12700,34500,12200,9.12,9.15,9.16,9.17,9.18,4100,18300,6500,19100,16400,9.12,534,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,1.607393e+15,6591.0,24.0,19,SZ,95854000.0,1275600,1.024724e+07,8.02,8.01,8.00,7.99,7.98,7.97,200,564400,28400,32500,20900,8.02,8.03,8.04,8.05,8.06,103200,10600,75900,10300,10300,8.12,1027,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40111,42103.0,1.607393e+15,577079.0,24.0,850,SZ,100006000.0,27410988,1.240832e+08,4.42,4.42,4.41,4.40,4.39,4.38,138300,235900,368100,235700,204000,4.43,4.44,4.45,4.46,4.47,14300,186100,198833,201600,25100,4.65,10749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40112,42104.0,1.607393e+15,577080.0,24.0,858,SZ,100006000.0,3151260,8.557986e+08,270.24,270.23,270.21,270.20,270.18,270.16,100,400,1000,800,100,270.24,270.26,270.28,270.29,270.30,1000,1600,400,1800,300,271.55,14971,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40113,42105.0,1.607393e+15,577081.0,24.0,859,SZ,100006000.0,3373900,1.914191e+07,5.66,5.65,5.64,5.63,5.62,5.61,109100,119800,233400,104100,141900,5.66,5.67,5.68,5.69,5.70,11600,29500,92000,113300,32000,5.71,2032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40115,42107.0,1.607393e+15,577083.0,24.0,875,SZ,100006000.0,1199332,4.771878e+06,3.99,3.99,3.98,3.97,3.96,3.95,39200,1049500,341268,146500,220700,4.00,4.01,4.02,4.03,4.04,798800,200100,368400,106300,144800,3.97,818,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40117,42109.0,1.607393e+15,577085.0,24.0,880,SZ,100006000.0,299300,2.997348e+06,10.00,10.00,9.99,9.98,9.97,9.96,1500,21000,16300,38000,10800,10.01,10.03,10.04,10.05,10.06,1200,4800,100,4700,1800,10.00,504,NaN,NaN,NaN,NaN,NaN,NaN,NaN

0.03312037562262182

In [20]:
data2['cum_amount'].astype(str).apply(lambda x: x.split('.')[1]).unique()

array(['0'], dtype=object)

In [18]:
data2_1[(data2_1['StockID'] == 2) & (data2_1['cum_volume'] == 10930601)]['cum_amount'].iloc[0]

322013808.0

In [19]:
data1_1[(data1_1['StockID'] == 2) & (data1_1['cum_volume'] == 10930601)]['cum_amount'].iloc[0]

322013808.5

In [9]:
test[(np.isnan(test["sequenceNo_y"])) & (test['time_x'] > 100100000)]

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y
71782,75306.0,1.607393e+15,1112513.0,24.0,2,SZ,100103000.0,10930601,3.220138e+08,29.36,29.36,29.35,29.34,29.33,29.32,74200,121100,41000,76500,52000,29.37,29.38,29.39,29.40,29.42,22900,9700,27200,41200,2400,29.45,11081,NaN,NaN,NaN,NaN,NaN,NaN
71783,75307.0,1.607393e+15,1112519.0,24.0,1,SZ,100103000.0,14117578,2.666608e+08,18.76,18.76,18.75,18.74,18.73,18.72,11100,59084,75543,41400,166100,18.78,18.79,18.80,18.81,18.82,5800,5400,11600,49400,7594,18.92,13133,NaN,NaN,NaN,NaN,NaN,NaN
71784,75308.0,1.607393e+15,1112520.0,24.0,5,SZ,100103000.0,858196,2.210662e+06,2.58,2.58,2.57,2.56,2.55,2.54,209200,257204,419000,467500,114700,2.59,2.60,2.61,2.62,2.63,315100,504900,567200,245800,105800,2.57,284,NaN,NaN,NaN,NaN,NaN,NaN
71786,75310.0,1.607393e+15,1112522.0,24.0,9,SZ,100103000.0,7433038,5.384788e+07,7.26,7.26,7.25,7.24,7.23,7.22,159800,39400,38616,48700,47900,7.27,7.28,7.29,7.30,7.31,109300,138000,311960,532100,177523,7.17,3692,NaN,NaN,NaN,NaN,NaN,NaN
71787,75311.0,1.607393e+15,1112523.0,24.0,20,SZ,100103000.0,658773,6.734487e+06,10.15,10.14,10.13,10.12,10.11,10.10,100,20600,21000,29900,27900,10.15,10.16,10.17,10.20,10.21,1000,4400,5800,2400,11800,10.10,828,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207586,1280415.0,1.607395e+15,14635676.0,24.0,300769,SZ,103739000.0,953074,1.592852e+08,166.50,166.30,166.20,166.18,166.01,166.00,8000,100,200,300,900,166.50,166.60,167.00,167.05,167.08,1200,100,500,100,300,162.50,4888,NaN,NaN,NaN,NaN,NaN,NaN
1207591,1280421.0,1.607395e+15,14635682.0,24.0,300770,SZ,103739000.0,2229645,1.708819e+08,76.40,76.38,76.37,76.36,76.33,76.32,2300,800,1500,500,200,76.39,76.40,76.47,76.53,76.62,200,1400,100,100,100,76.58,7378,NaN,NaN,NaN,NaN,NaN,NaN
1207592,1280422.0,1.607395e+15,14635683.0,24.0,300773,SZ,103739000.0,2446283,8.073233e+07,32.97,32.96,32.95,32.94,32.93,32.92,1500,5500,1500,500,900,32.97,32.98,32.99,33.00,33.01,6400,7400,2800,500,4100,33.01,4563,NaN,NaN,NaN,NaN,NaN,NaN
1207593,1280423.0,1.607395e+15,14635684.0,24.0,300776,SZ,103739000.0,555527,7.059842e+07,124.33,124.32,124.31,124.30,124.28,124.24,800,700,900,500,100,124.33,124.34,124.49,124.50,124.67,600,200,500,817,300,126.80,3101,NaN,NaN,NaN,NaN,NaN,NaN
1207594,1280424.0,1.607395e+15,14635685.0,24.0,300778,SZ,103739000.0,201425,6.152662e+06,30.76,30.75,30.73,30.62,30.60,30.59,3400,2500,400,100,1900,30.76,30.77,30.78,30.79,30.80,700,200,2000,1300,36200,30.47,814,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pd.set_option('max_columns', 200)
display(data1[(data1['StockID'] == 2) & (data1['cum_volume'] == 10343101)])
display(data2[(data2['StockID'] == 2)].head())

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
0,1607392734628721,6586,24,2,SZ,95854000,10343101,3.047514e+08,29.42,29.42,29.41,29.4,29.39,29.38,400,41100,27600,30400,46600,29.43,29.44,29.45,29.46,29.48,2500,20000,3500,3800,3400,29.45,10285

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
1550,1607392809630776,34537,31,2,SZ,100009000,10785101,317739263.0,29.39,29.38,29.37,29.36,29.35,29.34,100,300,73100,124400,40800,29.39,29.40,29.42,29.43,29.44,31800,25500,27800,600,17400,29.45,10848
3377,1607392812632548,71325,31,2,SZ,100012000,10796901,318085955.0,29.38,29.37,29.36,29.35,29.34,29.33,200,73100,124400,40800,76200,29.38,29.39,29.40,29.42,29.43,500,31000,25500,27800,600,29.45,10871
5181,1607392815735972,107034,31,2,SZ,100015000,10809601,318458954.0,29.37,29.37,29.36,29.35,29.34,29.33,2000,75400,124400,40800,76200,29.38,29.39,29.40,29.42,29.43,1700,32500,25500,27800,600,29.45,10881
6964,1607392818630917,144514,31,2,SZ,100018000,10812901,318555905.0,29.38,29.38,29.37,29.36,29.35,29.34,9900,2900,75400,118900,40800,29.39,29.40,29.42,29.43,29.44,32300,25500,28400,600,17400,29.45,10892
8753,1607392821634301,181900,31,2,SZ,100021000,10823001,318852694.0,29.39,29.38,29.37,29.36,29.35,29.34,15200,3800,77400,119300,40800,29.39,29.40,29.42,29.43,29.44,28100,40500,28400,600,17400,29.45,10906

In [22]:
# speed check
test1 = test[~np.isnan(test["sequenceNo_x"])]
test1 = test1[~np.isnan(test1["sequenceNo_y"])]
diff = test1["clockAtArrival_y"] - test1["clockAtArrival_x"]
print(np.quantile(abs(diff[diff < 0]), 0.25))
print(np.median(abs(diff[diff < 0])))
print(np.quantile(abs(diff[diff < 0]), 0.75))
print(np.quantile(diff[diff > 0], 0.25))
print(np.median(diff[diff > 0]))
print(np.quantile(diff[diff > 0], 0.75))
print(sum(diff < 0)/len(diff))
print(sum(diff > 0)/len(diff))

1472.0
3323.0
5772.0
2553.0
3345.0
4187.0
0.19405720628400674
0.8059128176711354

In [1]:
import pandas as pd
import random
import numpy as np
import pickle

TradeLog1 = pd.read_csv(r'//mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.161/Logs_full/mdTradeLog_20201208_1000.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum", "mdSource"]]
OrderLog1 = pd.read_csv(r'/mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.161/Logs_full/mdOrderLog_20201208_1000.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty", "mdSource"]]
TradeLog = pd.read_csv(r'/mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.164/Logs_full/mdTradeLog_20201208_0958.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum", "mdSource"]]
OrderLog = pd.read_csv(r'/mnt/data/20201208/zs_6801/zs_6801_20201208_168.26.0.164/Logs_full/mdOrderLog_20201208_0958.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty", "mdSource"]]
stocks = list(set(OrderLog1["SecurityID"].unique()) & set(OrderLog["SecurityID"].unique()))
display(len(stocks))
OrderLogSZ = OrderLog[OrderLog["SecurityID"].isin(stocks)]
OrderLogSZ1 = OrderLog1[OrderLog1["SecurityID"].isin(stocks)]
del OrderLog
del OrderLog1
TradeLogSZ = TradeLog[TradeLog["SecurityID"].isin(stocks)]
TradeLogSZ1 = TradeLog1[TradeLog1["SecurityID"].isin(stocks)]
del TradeLog
del TradeLog1
OrderLogSZ["OrderType"] = OrderLogSZ["OrderType"].apply(lambda x: str(x))
OrderLogSZ1["OrderType"] = OrderLogSZ1["OrderType"].apply(lambda x: str(x))
print(len(OrderLogSZ["SecurityID"].unique()))
print(len(OrderLogSZ1["SecurityID"].unique()))
print(len(TradeLogSZ["SecurityID"].unique()))
print(len(TradeLogSZ1["SecurityID"].unique()))
print(OrderLogSZ["mdSource"].unique())
print(OrderLogSZ1["mdSource"].unique())
print(TradeLogSZ["mdSource"].unique())
print(TradeLogSZ1["mdSource"].unique())
print(OrderLogSZ["exchId"].unique())
print(OrderLogSZ1["exchId"].unique())
print(TradeLogSZ["exchId"].unique())
print(TradeLogSZ1["exchId"].unique())

/home/work516/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

2128

2128
2128
2128
2128
[24]
[31]
[24]
[31]
[2]
[2]
[2]
[2]

In [2]:
TradeLogSZ["ExecType"] = TradeLogSZ["ExecType"].apply(lambda x: str(x))
TradeLogSZ1["ExecType"] = TradeLogSZ1["ExecType"].apply(lambda x: str(x))

# TradeLogSZ = TradeLogSZ[TradeLogSZ['TransactTime'] >= TradeLogSZ1['TransactTime'].min()]
columns = ["TransactTime","ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]
# columns = ["TransactTime","ApplSeqNum", "SecurityID", "ExecType", "TradePrice", "TradeQty", "BidApplSeqNum","OfferApplSeqNum"]

# TradeLogSZ1 = TradeLogSZ1.drop_duplicates(columns, keep='first')

re = pd.merge(TradeLogSZ, TradeLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = re["sequenceNo_x"].count()
n2 = re["sequenceNo_y"].count()
len1 = len(re)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(re[np.isnan(re["sequenceNo_y"])])
    print(len(re[np.isnan(re["sequenceNo_y"])]))
    print(np.sort(re[np.isnan(re["sequenceNo_y"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique())
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(re[np.isnan(re["sequenceNo_x"])])
    print(np.sort(re[np.isnan(re["sequenceNo_x"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique())
    display(n2-n1)

6291548
24816997
25068242
-----------------------------------------------

'test is not complete:'

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,mdSource_x,clockAtArrival_y,sequenceNo_y,exchId_y,mdSource_y
0,1.607393e+15,5.0,2.0,95853570,5460778,157,F,N,102300,300,30690000,5460777,5452424,24.0,NaN,NaN,NaN,NaN
1,1.607393e+15,8.0,2.0,95853570,5460780,300026,F,N,50200,10000,502000000,5460779,5415922,24.0,NaN,NaN,NaN,NaN
2,1.607393e+15,13.0,2.0,95853570,5460782,300747,F,N,788400,800,630720000,5460781,5457809,24.0,NaN,NaN,NaN,NaN
3,1.607393e+15,15.0,2.0,95853570,4879008,300501,F,N,232000,700,162400000,4879007,4872316,24.0,NaN,NaN,NaN,NaN
4,1.607393e+15,16.0,2.0,95853570,4879009,300501,F,N,232000,300,69600000,4879007,4872608,24.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251240,1.607393e+15,576901.0,2.0,100006720,5613578,2594,F,N,1819900,100,181990000,5613571,5608441,24.0,NaN,NaN,NaN,NaN
251241,1.607393e+15,576919.0,2.0,100006720,5411488,300488,F,N,186800,100,18680000,5411487,5411470,24.0,NaN,NaN,NaN,NaN
251244,1.607393e+15,576941.0,2.0,100006720,5613582,300497,F,N,150800,2000,301600000,5603428,5613581,24.0,NaN,NaN,NaN,NaN
251250,1.607393e+15,576951.0,2.0,100006720,5880455,686,4,N,0,500,0,0,5654514,24.0,NaN,NaN,NaN,NaN
251253,1.607393e+15,576962.0,2.0,100006730,5880458,786,F,N,392000,100,39200000,5880457,5868186,24.0,NaN,NaN,NaN,NaN

251245
[ 95853570  95853580  95853590 ... 100006710 100006720 100006730]
2120
[   157 300026 300747 ...   2356   2033   2336]

In [3]:
# speed test
re = re[~re["sequenceNo_x"].isnull()]
re = re[~re["sequenceNo_y"].isnull()]
diff = re["clockAtArrival_y"] - re["clockAtArrival_x"]
re["diff"] = re["clockAtArrival_y"] - re["clockAtArrival_x"]
print(np.quantile(abs(diff[diff < 0]), 0.25))
print(np.median(abs(diff[diff < 0])))
print(np.quantile(abs(diff[diff < 0]), 0.75))
print(np.quantile(diff[diff > 0], 0.25))
print(np.median(diff[diff > 0]))
print(np.quantile(diff[diff > 0], 0.75))
print(sum(diff < 0)/len(diff))
print(sum(diff > 0)/len(diff))
print(sum(diff == 0)/len(diff))

1487.5
4476.0
5926.0
2428.0
3026.0
3884.0
1.1588822613700009e-05
0.9999882456227775
1.6555460876714298e-07

In [4]:
columns = ["TransactTime", "ApplSeqNum","Side",'OrderType', 'Price', 'OrderQty', "SecurityID"]

# OrderLogSZ = OrderLogSZ[OrderLogSZ['TransactTime'] >= OrderLogSZ1['TransactTime'].min()]
ree = pd.merge(OrderLogSZ, OrderLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = ree["sequenceNo_x"].count()
n2 = ree["sequenceNo_y"].count()
len1 = len(ree)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(ree[np.isnan(ree["sequenceNo_y"])])
    print(len(ree[np.isnan(ree["sequenceNo_y"])]))
    print(np.sort(ree[np.isnan(ree["sequenceNo_y"])]["TransactTime"].unique()))
    print(len(ree[np.isnan(ree["sequenceNo_y"])]["SecurityID"].unique()))
    print(ree[np.isnan(ree["sequenceNo_y"])]["SecurityID"].unique())
if (len1 == n2) & (n1 < len1):
    display("test is complete, baseline is not complete:")
    display(ree[np.isnan(ree["sequenceNo_x"])])
    print(np.sort(ree[np.isnan(ree["sequenceNo_x"])]["TransactTime"].unique()))
    print(len(ree[np.isnan(ree["sequenceNo_x"])]["SecurityID"].unique()))
    print(ree[np.isnan(ree["sequenceNo_x"])]["SecurityID"].unique())
    display(n2-n1)

7064401
26526157
26809763
-----------------------------------------------

'test is not complete:'

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,Side,OrderType,Price,OrderQty,mdSource_x,clockAtArrival_y,sequenceNo_y,exchId_y,mdSource_y
0,1.607393e+15,1.0,2.0,95853570,5733096,2342,1,2,37800,1000,24.0,NaN,NaN,NaN,NaN
1,1.607393e+15,2.0,2.0,95853570,5733097,2131,1,2,33100,25400,24.0,NaN,NaN,NaN,NaN
2,1.607393e+15,3.0,2.0,95853570,4879005,2782,2,2,142800,1000,24.0,NaN,NaN,NaN,NaN
3,1.607393e+15,4.0,2.0,95853570,5460777,157,1,2,102400,300,24.0,NaN,NaN,NaN,NaN
4,1.607393e+15,6.0,2.0,95853570,4879006,300458,2,2,384000,2000,24.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283605,1.607393e+15,576954.0,2.0,100006720,5880456,2589,2,2,60800,1700,24.0,NaN,NaN,NaN,NaN
283610,1.607393e+15,576961.0,2.0,100006730,5880457,786,1,2,392000,100,24.0,NaN,NaN,NaN,NaN
283611,1.607393e+15,576963.0,2.0,100006730,5880459,786,1,2,392000,100,24.0,NaN,NaN,NaN,NaN
283619,1.607393e+15,576979.0,2.0,100006730,5613591,826,2,2,77600,2200,24.0,NaN,NaN,NaN,NaN
283621,1.607393e+15,576981.0,2.0,100006730,5613592,826,2,2,77600,2800,24.0,NaN,NaN,NaN,NaN

283606
[ 95853570  95853580  95853590 ... 100006710 100006720 100006730]
2128
[2342 2131 2782 ... 2336 2872 2692]

In [5]:
ree = ree[~ree["sequenceNo_x"].isnull()]
ree = ree[~ree["sequenceNo_y"].isnull()]
ree["diff"] = ree["clockAtArrival_y"] - ree["clockAtArrival_x"]
diff = ree["clockAtArrival_y"] - ree["clockAtArrival_x"]
print(np.quantile(abs(diff[diff < 0]), 0.25))
print(np.median(abs(diff[diff < 0])))
print(np.quantile(abs(diff[diff < 0]), 0.75))
print(np.quantile(diff[diff > 0], 0.25))
print(np.median(diff[diff > 0]))
print(np.quantile(diff[diff > 0], 0.75))
print(sum(diff < 0)/len(diff))
print(sum(diff > 0)/len(diff))

2568.75
4509.5
8122.0
1816.0
2304.0
3199.0
1.563238528815574e-05
0.9999843676147119

In [3]:
TradeLogSZ1["tradeseq"] = TradeLogSZ1.index.values
OrderLogSZ1["orderseq"] = OrderLogSZ1.index.values
SZ = pd.concat([TradeLogSZ, OrderLogSZ]).sort_values(by=["sequenceNo", "clockAtArrival"])
SZ1 = pd.concat([TradeLogSZ1, OrderLogSZ1]).sort_values(by=["sequenceNo", "clockAtArrival"])
del TradeLogSZ
# del TradeLogSZ1
del OrderLogSZ
# del OrderLogSZ1

print(len(SZ["SecurityID"].unique()))
print(len(SZ1["SecurityID"].unique()))

columns = ["TransactTime", "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag", "TradePrice", "TradeQty",
           "TradeMoney", "BidApplSeqNum", "OfferApplSeqNum", "Side", "OrderType", "Price", "OrderQty"]
# columns = ["TransactTime", "ApplSeqNum", "SecurityID", "ExecType", "TradePrice", "TradeQty",
#            "BidApplSeqNum", "OfferApplSeqNum", "Side", "OrderType", "Price", "OrderQty"]
stocks = SZ["SecurityID"].unique()
m = 0
diff = []
for i in stocks:
    re1 = pd.merge(SZ[SZ["SecurityID"] == i], SZ1[SZ1["SecurityID"] == i], left_on=columns, right_on=columns, how="inner")
    if (sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]).any() == False:
        m = m + 1
    else:
        diff.append(i)
if m == len(stocks):
    print("SZE Trade + Order Data have same ordering within stocks")
print(m)
print(diff)

# if len(diff) != 0:
#     for i in diff:
#         re1 = pd.merge(SZ[SZ["SecurityID"] == i], SZ1[SZ1["SecurityID"] == i], left_on=columns, right_on=columns, how="inner")
#         display(re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]])

2129
2129
SZE Trade + Order Data have same ordering within stocks
2129
[]

In [5]:
if len(diff) != 0:
    for i in diff:
        re1 = pd.merge(SZ[SZ["SecurityID"] == i], SZ1[SZ1["SecurityID"] == i], left_on=columns, right_on=columns, how="inner")
        display(re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]])

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,...,Side,OrderType,Price,OrderQty,clockAtArrival_y,sequenceNo_y,exchId_y,mdSource_y,tradeseq,orderseq
69001,1605681020815736,203856188,2,143013560,18949165,300301,NaN,NaN,NaN,NaN,...,2.0,2,48600.0,40000.0,1605681069762172,203123567,2,24,NaN,40559804.0
69002,1605681020815776,203856190,2,143013560,18949167,300301,F,N,48600.0,13500.0,...,NaN,NaN,NaN,NaN,1605681069762165,203123566,2,24,52508678.0,NaN